<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-N7T8FIF4" failures="1" tests="5" name="smoke" time="35.211" errors="0" timestamp="2022-11-01T23:05:20 IST">
  <testcase classname="com.supermarket1.tests.LogInTest" name="Verify_RememberMeCheckBox" time="0.276"/>
  <testcase classname="com.supermarket1.tests.LogInTest" name="verify_InvalidData" time="0.493">
    <failure type="java.lang.AssertionError" message="This is testcase failed expected [� Alert!] but found [×
Alert!
Invalid Username/Password]">
      <![CDATA[java.lang.AssertionError: This is testcase failed expected [� Alert!] but found [×
Alert!
Invalid Username/Password]
at com.supermarket1.tests.LogInTest.verify_InvalidData(LogInTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- verify_InvalidData -->
  <testcase classname="com.supermarket1.tests.LogInTest" name="verify_LogIn" time="0.579"/>
  <testcase classname="com.supermarket1.tests.LogInTest" name="verify_LogOut" time="1.431"/>
  <testcase classname="com.supermarket1.tests.PushNotificationTest" name="verify_PushNotification" time="4.183"/>
</testsuite> <!-- smoke -->
